### PR TITLE
Fix wrong share link

### LINKED ISSUE #32: Wrong link when sharing proposal
seeing this bug here: https://xdai.alchemy.do/dao/0xe3a89ed4956c4f7173418e4dec2a77a5f60807de/proposal/0x2ce3d108986bd5538dea9b7ba39df4d701325f442fd2a3397f59d7996c73166a

'share' copy's this address

https://alchemy.daostack.io/dao/0xe3a89ed4956c4f7173418e4dec2a77a5f60807de/proposal/0x2ce3d108986bd5538dea9b7ba39df4d701325f442fd2a3397f59d7996c73166a

### PR DESCRIPTION
**Pull request by roienatan**
resolves: https://github.com/daostack/alchemy_2/issues/32

### CODE REVIEW

File: src/components/Proposal/ProposalDetailsPage.tsx [hunk 1]
```diff
@@ -337,7 +337,7 @@ class ProposalDetailsPage extends React.Component<IProps, IState> {
         {this.state.showShareModal ?
           <SocialShareModal
             closeHandler={this.closeShareModal}
-            url={`https://alchemy.daostack.io/dao/${daoState.address}/proposal/${proposalState.id}`}
+            url={`https://${targetedNetwork()}.alchemy.do/dao/${daoState.address}/proposal/${proposalState.id}`}
```
Comment (orenyodfat) [inline src/components/Proposal/ProposalDetailsPage.tsx]: this not work on mainnet

**Review by orenyodfat — APPROVED** [review]

**Review by orenyodfat — APPROVED** [review]
